apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      type: mysql
  template:
    metadata:
      labels:
        type: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:custom
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root_password.txt
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database_name.txt
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc


---

